zrl/models.py
from sqlalchemy import Column, Integer, String
from zrl.database import Base


class Mapping(Base):
    __tablename__ = 'mapping'

    id = Column(Integer, primary_key=True)
    tag = Column(String(2048), unique=True)
    url = Column(String(2048), unique=False)
    hits = Column(Integer, default=0)

    def __init__(self, tag=None, url=None):
        self.tag = tag
        self.url = url

    def __repr__(self):
        return f'{self.tag} - {self.url}'

zrl/__init__.py
import os
from flask import Flask
from flask_migrate import Migrate
from zrl import views


def create_app(test_config=None):
    # create and configure the app
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_mapping(
        SECRET_KEY='dev',
    )

    app.register_blueprint(views.bp)

    # Database
    from zrl import database
    app.teardown_appcontext(database.shutdown_session)
    app.cli.add_command(database.init_db_command)
    migrate = Migrate(app, database.db_session)

    if test_config is None:
        # load the instance config, if it exists, when not testing
        app.config.from_pyfile('config.py', silent=True)
    else:
        # load the test config if passed in
        app.config.from_mapping(test_config)

    # ensure the instance folder exists
    try:
        os.makedirs(app.instance_path)
    except OSError:
        pass

    # a simple page that says hello
    @app.route('/hello')
    def hello():
        return 'Hello, World!'

    return app

zrl/views.py
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm.exc import NoResultFound
from zrl.database import db_session
from zrl.models import Mapping

from flask import (
    Blueprint, flash, render_template, request, redirect, abort
)

bp = Blueprint('views', __name__, url_prefix='/')


@bp.route('/zrl_edit/<int:mapping_id>')
def tag_edit(mapping_id):
    try:
        mapping = Mapping.query.filter(Mapping.id == mapping_id).one()
        return render_template('edit.html', mapping=mapping)
    except NoResultFound:
        abort(404)


@bp.route('/<path:path>')
def tag_resolver(path):

    if path.endswith('/'):
        path = path[:-1]

    r = Mapping.query.filter(Mapping.tag == path).first()

    # This tag doesn't exist: flash an error
    if r is None:
        flash(message=f'A mapping does not exist for "{path}"',
              category='error')
        return render_template('index.html')
    else:
        r.hits += 1
        db_session.commit()

    return redirect(r.url)


@bp.route('/', methods=('GET', 'POST'))
def index():

    if request.method == 'POST':

        try:
            m = Mapping(tag=request.form['tag'],
                        url=request.form['url'])
            db_session.add(m)
            db_session.commit()
        except IntegrityError as e:
            flash(message=f'Tag ({request.form["tag"]}) already exists in the database',
                  category='error')

    return render_template('index.html', mappings=Mapping.query.all())

zrl/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>

    {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
                <div class="row">
                <div class="col">
                    <div class="alert alert-warning" role="alert">
                      {{ message }}
                    </div>
                </div>
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}

    {% block content %}{% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

zrl/templates/edit.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
    <div class="col-6">
        <form method="POST">
            <div class="form-group">
                <label for="tag">Tag</label>
                <input class="form-control form-control-lg" type="text"
                       value="{{ mapping.tag }}" name="tag" id="tag" placeholder="Tag">
            </div>

            <div class="form-group">
                <label for="url">URL</label>
                <input class="form-control form-control-lg" type="url"
                       value="{{ mapping.url }}" name="url" id="url" placeholder="https://wherever.com">
            </div>

            <input type="submit" class="btn btn-primary">
        </form>
    </div>
    </div>
{% endblock %}

zrl/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="display-1">ZRL</h1>

    <div class="row">
    <div class="col-6">
        <form method="POST">
            <div class="form-group">
                <label for="tag">Tag</label>
                <input class="form-control form-control-lg" type="text" name="tag" id="tag" placeholder="Tag">
            </div>

            <div class="form-group">
                <label for="url">URL</label>
                <input class="form-control form-control-lg" type="url" name="url" id="url" placeholder="http://wherever.com">
            </div>

            <input type="submit" class="btn btn-primary">
        </form>
    </div>
    </div>

    <div class="row mt-5">
    <div class="col">
        <table class="table">
            <thead>
            <th>Tag</th>
            <th>URL</th>
            <th>Hits</th>
            <th></th>
            </thead>
        {% for mapping in mappings %}
            <tr>
            <td>{{ mapping.tag }}</td>
            <td>{{ mapping.url }}</td>
            <td>{{ mapping.hits }}</td>
            <td><a href="{{ url_for('views.tag_edit', mapping_id=mapping.id)}}">edit</a></td>
            </tr>
        {% endfor %}
        </table>
    </div>
    </div>
{% endblock %}